npc = NPCText()
npc.setText(npc.root, 'ARE YOU SCREWING THE SHEEP?')
op2 = npc.addOption(npc.root, "No", "Oh, okay")
op1 = npc.addOption(npc.root, "Yes", "YOU'RE GOING TO DIE")
npc.setAction(op1, "self.terminated = True")
npc.setAction(op2, "self.terminated = True")